import React, { useState, useEffect, useRef } from 'react';
import { Bell } from 'lucide-react';
import { NOTIFICATION_PAGE_SIZE } from '../common/common_staff_notification';
import { NotificationAPI } from '../../api/communication';
import { shouldReceiveNotification } from '../common/common_admin_notification';

/**
 * STAFF ③ 알림 사항 컴포넌트
 * 직원 모드에서 회사 알림을 확인하는 컴포넌트 (카드 + 더보기 팝업 포함)
 */
const StaffNotification = ({ currentUser, getText, selectedLanguage }) => {
  const [expandedNotification, setExpandedNotification] = useState(null);
  const [showNotificationMorePopup, setShowNotificationMorePopup] =
    useState(false);
  const [notificationPage, setNotificationPage] = useState(1);
  const [employeeNotifications, setEmployeeNotifications] = useState([]);
  const [localReadNotifications, setLocalReadNotifications] = useState(
    new Set()
  );
  const notificationScrollRef = useRef(null);

  // localStorage에서 읽은 알림 ID 로드
  useEffect(() => {
    if (!currentUser?.id) return;

    const storageKey = `readNotifications_${currentUser.id}`;
    const stored = localStorage.getItem(storageKey);
    if (stored) {
      try {
        const readIds = JSON.parse(stored);
        setLocalReadNotifications(new Set(readIds));
      } catch (error) {
        console.error('읽은 알림 로드 실패:', error);
      }
    }
  }, [currentUser?.id]);

  // 알림을 읽음으로 표시
  const markNotificationAsRead = (notificationId) => {
    if (!currentUser?.id) return;

    setLocalReadNotifications((prev) => {
      const newSet = new Set(prev);
      newSet.add(notificationId);

      // localStorage에 저장
      const storageKey = `readNotifications_${currentUser.id}`;
      localStorage.setItem(storageKey, JSON.stringify([...newSet]));

      return newSet;
    });
  };

  // 읽지 않은 알림 개수 계산
  const getUnreadNotificationCount = () => {
    return employeeNotifications.filter(
      (notification) =>
        !localReadNotifications.has(notification._id || notification.id)
    ).length;
  };

  // 5일 만료 체크 함수
  const isExpired5Days = (createdAt) => {
    if (!createdAt) return true;
    const now = new Date().getTime();
    const created = new Date(createdAt).getTime();
    const fiveDaysInMs = 5 * 24 * 60 * 60 * 1000;
    return now - created > fiveDaysInMs;
  };

  // 한국 시간 형식으로 변환 (YYYY-MM-DD HH:mm:ss)
  const formatKoreanTime = (isoString) => {
    if (!isoString) return '';
    const date = new Date(isoString);

    // 한국 시간대로 변환 (+9시간)
    const koreanTime = new Date(date.getTime() + 9 * 60 * 60 * 1000);

    // YYYY-MM-DD HH:mm:ss 형식으로 변환
    const year = koreanTime.getUTCFullYear();
    const month = String(koreanTime.getUTCMonth() + 1).padStart(2, '0');
    const day = String(koreanTime.getUTCDate()).padStart(2, '0');
    const hours = String(koreanTime.getUTCHours()).padStart(2, '0');
    const minutes = String(koreanTime.getUTCMinutes()).padStart(2, '0');
    const seconds = String(koreanTime.getUTCSeconds()).padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  };

  // ✅ DB에서 직접 알림 데이터 로드
  useEffect(() => {
    const loadNotifications = async () => {
      if (!currentUser?.id) return;

      try {
        const response = await NotificationAPI.list();

        // response가 바로 배열로 반환됨
        const notificationData = Array.isArray(response)
          ? response
          : response.data || [];

        if (notificationData.length > 0) {
          // App.js의 updateEmployeeNotifications와 동일한 필터링 로직
          const filteredNotifications = notificationData.filter(
            (notification) => {
              // 5일 이상 지난 알림 제외
              const expired = isExpired5Days(notification.createdAt);
              if (expired) return false;

              // 수신 대상 체크
              const shouldReceive = shouldReceiveNotification(
                notification,
                currentUser
              );
              if (!shouldReceive) return false;

              // 자동생성된 본인의 신청 알림은 제외
              if (
                notification.isAutoGenerated &&
                notification.title &&
                (notification.title.includes('연차 신청') ||
                  notification.title.includes('건의사항 신청')) &&
                notification.title.includes(currentUser.name)
              ) {
                return false;
              }

              return true;
            }
          );

          setEmployeeNotifications(filteredNotifications);
        }
      } catch (error) {
        console.error('알림 데이터 로드 실패:', error);
      }
    };

    loadNotifications();
  }, [currentUser?.id]);

  // 팝업이 열리거나 페이지가 변경될 때 스크롤을 맨 위로
  useEffect(() => {
    if (showNotificationMorePopup && notificationScrollRef.current) {
      notificationScrollRef.current.scrollTop = 0;
    }
  }, [showNotificationMorePopup, notificationPage]);

  // 최신순으로 정렬 (createdAt 기준 내림차순)
  const sortedNotifications = [...employeeNotifications].sort((a, b) => {
    return new Date(b.createdAt) - new Date(a.createdAt);
  });

  return (
    <>
      {/* 알림 사항 카드 */}
      <div className="bg-white p-4 rounded-2xl shadow-sm border border-orange-100">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center">
            <Bell className="w-5 h-5 text-orange-500 mr-2" />
            <h3 className="text-sm font-semibold text-gray-800">
              {getText('알림 사항', 'Notifications')}
            </h3>
            {getUnreadNotificationCount() > 0 && (
              <span
                className="ml-2 bg-red-500 text-white text-2xs rounded-full px-1.5 py-0.5 min-w-[20px] text-center font-bold
            "
              >
                {getUnreadNotificationCount()}
              </span>
            )}
          </div>
          <button
            onClick={() => {
              setNotificationPage(1);
              setShowNotificationMorePopup(true);
            }}
            className="text-blue-500 text-2xs hover:text-orange-600"
          >
            {getText('더보기', 'More')} &gt;
          </button>
        </div>
        <div className="space-y-0.5">
          {sortedNotifications.slice(0, 3).map((notification) => {
            const notificationId = notification._id || notification.id;
            const isUnread = !localReadNotifications.has(notificationId);
            const isExpanded = expandedNotification === notificationId;
            return (
              <div
                key={`notification-${notificationId}`}
                className="border-b border-gray-100 last:border-b-0"
              >
                <div
                  className="flex items-center justify-between p-2 hover:bg-blue-50 rounded-lg cursor-pointer"
                  onClick={() => {
                    if (isUnread) {
                      markNotificationAsRead(notificationId);
                    }
                    setExpandedNotification(isExpanded ? null : notificationId);
                  }}
                >
                  <div className="flex-1 flex items-center">
                    <span
                      className={`text-xs font-semibold ${
                        isUnread
                          ? 'font-semibold text-gray-900'
                          : 'text-gray-700'
                      }`}
                    >
                      {notification.title}
                    </span>
                    {isUnread && (
                      <span className="ml-2 bg-red-500 text-white text-2xs rounded-full px-1.5 py-0.5 font-bold text-center">
                        N
                      </span>
                    )}
                  </div>
                  <div className="text-2xs flex items-center ml-2">
                    <span className="text-gray-500 mr-1">
                      {formatKoreanTime(notification.createdAt)}
                    </span>
                    <span
                      className={`transform transition-transform duration-200 ${
                        isExpanded ? 'rotate-180' : ''
                      }`}
                    >
                      ▼
                    </span>
                  </div>
                </div>
                {isExpanded && (
                  <div className="px-2 pb-2">
                    <p className="text-xs text-gray-600 leading-relaxed">
                      {notification.content}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* 알림 전체 팝업 */}
      {showNotificationMorePopup && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl shadow-xl max-w-4xl w-full mx-4 max-h-[80vh] flex flex-col">
            <div className="p-6 pb-4 border-b border-gray-200">
              <div className="flex justify-between items-center">
                <h3 className="text-sm font-semibold text-gray-800">
                  {getText('전체 알림사항', 'All Notifications')}
                </h3>
                <button
                  onClick={() => setShowNotificationMorePopup(false)}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>
            </div>

            <div
              ref={notificationScrollRef}
              style={{
                height: '500px',
                overflowY: 'auto',
                padding: '1.5rem',
              }}
            >
              <div className="space-y-2">
                {sortedNotifications
                  .slice(
                    (notificationPage - 1) * NOTIFICATION_PAGE_SIZE,
                    notificationPage * NOTIFICATION_PAGE_SIZE
                  )
                  .map((notification) => {
                    const notificationId = notification._id || notification.id;
                    const isUnread =
                      !localReadNotifications.has(notificationId);
                    return (
                      <div
                        key={`notification-${notificationId}`}
                        className="border border-gray-200 rounded-lg p-4 bg-gray-50 cursor-pointer hover:bg-gray-100"
                        onClick={() => {
                          if (isUnread) {
                            markNotificationAsRead(notificationId);
                          }
                        }}
                      >
                        <div className="flex justify-between items-start mb-2">
                          <div className="flex items-center">
                            <h4
                              className={`text-xs font-medium ${
                                isUnread
                                  ? 'text-gray-900 font-semibold'
                                  : 'text-gray-800'
                              }`}
                            >
                              {notification.title}
                            </h4>
                            {isUnread && (
                              <span className="ml-2 bg-red-500 text-white text-xs rounded-full px-1.5 py-0.5 font-bold">
                                N
                              </span>
                            )}
                          </div>
                          <span className="text-xs text-gray-500 ml-2">
                            {formatKoreanTime(notification.createdAt)}
                          </span>
                        </div>
                        <p
                          className={`text-xs ${
                            isUnread ? 'text-gray-700' : 'text-gray-600'
                          }`}
                        >
                          {notification.content}
                        </p>
                      </div>
                    );
                  })}
                {sortedNotifications.length === 0 && (
                  <div className="text-center text-gray-500 py-8">
                    <p className="text-xs">
                      {getText('알림이 없습니다', 'No Notifications')}
                    </p>
                    <p className="text-xs">
                      {getText(
                        '새로운 알림이 있을 때 여기에 표시됩니다',
                        'New notifications will appear here'
                      )}
                    </p>
                  </div>
                )}
              </div>

              {/* 페이지네이션 */}
              {sortedNotifications.length > 0 && (
                <div className="flex justify-center items-center mt-6 space-x-2">
                  <button
                    onClick={() =>
                      setNotificationPage(Math.max(1, notificationPage - 1))
                    }
                    disabled={notificationPage === 1}
                    className="px-3 py-1 text-xs border rounded disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
                  >
                    {selectedLanguage === 'en' ? 'Prev' : '이전'}
                  </button>
                  <span className="text-xs text-gray-600">
                    {notificationPage} /{' '}
                    {Math.max(
                      1,
                      Math.ceil(
                        sortedNotifications.length / NOTIFICATION_PAGE_SIZE
                      )
                    )}
                  </span>
                  <button
                    onClick={() =>
                      setNotificationPage(
                        Math.min(
                          Math.ceil(
                            sortedNotifications.length / NOTIFICATION_PAGE_SIZE
                          ),
                          notificationPage + 1
                        )
                      )
                    }
                    disabled={
                      notificationPage >=
                      Math.ceil(
                        sortedNotifications.length / NOTIFICATION_PAGE_SIZE
                      )
                    }
                    className="px-3 py-1 text-xs border rounded disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
                  >
                    {selectedLanguage === 'en' ? 'Next' : '다음'}
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default StaffNotification;
